{% set name = "django-cms" %}
{% set version = "3.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-cms-{{ version }}.tar.gz
  sha256: 58ff8bda97f0012fe365eaa542f1c91a310c6b774030ef5d6c2c3caaabf3cf31

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=3.2,<5.0
    - django-classy-tags >=0.7.2
    - django-formtools >=2.1
    - django-treebeard >=4.3
    - django-sekizai >=0.7
    - djangocms-admin-style >=1.2
    - packaging

test:
  imports:
    - cms
    - menus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.django-cms.org/
  summary: Lean enterprise content management powered by Django.
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - cms/static/cms/js/select2/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
